### ISSUE TITLE
Line Items on the Team Expense Breakdown will be Generated from input Files

### ISSUE THREAD

**Issue by PaulEllis2001** [cs481-ekh/s23-totalled#47]
- [x] #73 Take input list of Sheets from workbooks and find column headings for each sheet
 - [x] #74 Filter out rows that don't have a Senior Design PO
 - [x] #75 With remaining rows take data and populate a list of Team Objects
